-- Inventory/pricing calendar per spa/service/day
CREATE TABLE inventory_calendar (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    spa_id BIGINT NOT NULL,
    service_id BIGINT,
    service_date DATE NOT NULL,
    available_units INTEGER NOT NULL,
    base_price_cents INTEGER NOT NULL,
    override_price_cents INTEGER,
    currency VARCHAR(10) NOT NULL,
    locked BOOLEAN NOT NULL,
    note VARCHAR(1000),
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT fk_inventory_calendar_spa FOREIGN KEY (spa_id) REFERENCES spa(id),
    CONSTRAINT fk_inventory_calendar_service FOREIGN KEY (service_id) REFERENCES service(id)
);
CREATE UNIQUE INDEX uk_inventory_calendar_spa_service_date ON inventory_calendar (spa_id, service_id, service_date);
CREATE INDEX idx_inventory_calendar_spa_date ON inventory_calendar (spa_id, service_date);
CREATE INDEX idx_inventory_calendar_service_date ON inventory_calendar (service_id, service_date);

-- Blackout management
CREATE TABLE blackout_window (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    spa_id BIGINT NOT NULL,
    provider_id BIGINT,
    start_ts TIMESTAMP WITH TIME ZONE NOT NULL,
    end_ts TIMESTAMP WITH TIME ZONE NOT NULL,
    reason VARCHAR(500),
    created_by VARCHAR(100),
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT fk_blackout_spa FOREIGN KEY (spa_id) REFERENCES spa(id),
    CONSTRAINT fk_blackout_provider FOREIGN KEY (provider_id) REFERENCES provider_user(id)
);
CREATE INDEX idx_blackout_spa ON blackout_window (spa_id, start_ts, end_ts);
CREATE INDEX idx_blackout_provider ON blackout_window (provider_id, start_ts, end_ts);

-- Provider/admin audit logs
CREATE TABLE provider_audit_log (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    spa_id BIGINT,
    actor_type VARCHAR(50),
    actor_id BIGINT,
    action VARCHAR(150) NOT NULL,
    details VARCHAR(4000),
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT fk_provider_audit_spa FOREIGN KEY (spa_id) REFERENCES spa(id)
);
CREATE INDEX idx_provider_audit_spa ON provider_audit_log (spa_id, created_at);
CREATE INDEX idx_provider_audit_actor ON provider_audit_log (actor_type, actor_id);

-- Support override workflows
CREATE TABLE support_override (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    spa_id BIGINT,
    booking_id BIGINT,
    override_type VARCHAR(100) NOT NULL,
    status VARCHAR(20) NOT NULL,
    payload VARCHAR(4000),
    requested_by VARCHAR(100),
    resolved_by VARCHAR(100),
    resolved_at TIMESTAMP WITH TIME ZONE,
    resolution_notes VARCHAR(1000),
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT fk_support_override_spa FOREIGN KEY (spa_id) REFERENCES spa(id),
    CONSTRAINT fk_support_override_booking FOREIGN KEY (booking_id) REFERENCES booking(id)
);
CREATE INDEX idx_support_override_spa ON support_override (spa_id, created_at);
CREATE INDEX idx_support_override_booking ON support_override (booking_id);
